/**
 * Migration: Create ai_recommendations table
 *
 * Advisory recommendations generated by the AI layer.
 * Each has a reasoning field in plain language and can expire
 * when the underlying conditions become irrelevant.
 *
 * Forward-only migration per Rule 6.
 */

import type { Knex } from "knex";

export async function up(knex: Knex): Promise<void> {
  await knex.raw(`
    CREATE TYPE recommendation_severity AS ENUM (
      'informational', 'advisory', 'warning'
    )
  `);

  await knex.schema.createTable("ai_recommendations", (table) => {
    table.uuid("id").primary().notNullable();
    table.uuid("user_id").notNullable().references("id").inTable("users").onDelete("CASCADE");
    table.string("recommendation_type", 100).notNullable();
    table.text("content").notNullable();
    table.text("reasoning").notNullable();
    table.boolean("is_dismissed").notNullable().defaultTo(false);
    table.timestamp("dismissed_at", { useTz: true }).nullable();
    table.uuid("related_task_id").nullable().references("id").inTable("tasks").onDelete("SET NULL");
    table.specificType("severity", "recommendation_severity").notNullable();
    table.timestamp("generated_at", { useTz: true }).notNullable();
    table.timestamp("expires_at", { useTz: true }).nullable();
    table.timestamp("created_at", { useTz: true }).notNullable().defaultTo(knex.fn.now());

    // Indexes per Db.md
    table.index(["user_id", "is_dismissed"], "idx_recommendations_user_dismissed");
    table.index("related_task_id", "idx_recommendations_task");
    table.index("expires_at", "idx_recommendations_expires");
  });
}

export async function down(_knex: Knex): Promise<void> {
  throw new Error(
    "Down migrations are not supported. Write a corrective migration instead. (Rule 6)"
  );
}
